### ISSUE TITLE
Closed Tickets counter incorrect due to Timezone difference

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#9]
This is related to issue #2 but it effects the closed ticket count - i've also mentioned it in issue #5 .

The problem is that when your timezone is ahead of Autotask, you can have issues seeing any data when a single day is retrieved from Autotask API - specifically using the the "now" or "today" annotations.
I've been able to prove this now by adjusting the GetTicketsCompletedTodayTask.php file to build an array and collect 14 days worth of closed tickets, similar to how the GetOpenTickets routine works.

When I do this, the dates are transformed correctly when the data is saved to our database, and my completed count starts working...

**Comment by coencoppens** [comment]
@jarrodmast I've done some thinking, and it actually makes sense. Autotask stores and returns the data in EST. So it's fine to rebuild the output to your own timezone, but the query needs to request the correct date too.

I've created a branch (https://github.com/coencoppens/autotask-dashboards/tree/timezone) with a few very minor adjustments that you can test, I'm doing the same here at our office.

**Comment by coencoppens** [comment]
For details about the progress, see these comments:
https://github.com/coencoppens/autotask-dashboards/commit/f75d2e4119f9990d797e9e11285293cae42f8696#commitcomment-3995700

**Comment by coencoppens** [comment]
@jarrodmast I've changed the code so it takes into account an additional day, should resolve the issue. Can you give it a test run?

**Comment by jarrodmast** [comment]
Thanks @coencoppens i'm running my dash setup to pull 1.4.0 branch directly now. 
I'm still not getting any timeentries in my mysql database. 

The updated code works fine for closed ticket counts now though ;)
